#!/usr/bin/env bash
# Removes temporary JSON artifacts generated by the pipeline, with success/failure logging.
set -euo pipefail

cleanup_tmp_json() {
  local tmp_dir="$1"
  [[ -d "$tmp_dir" ]] || return 0

  local found=0
  local removed=0
  local failed=0
  local file
  while IFS= read -r file; do
    found=1
    if rm -f "$file"; then
      removed=$((removed + 1))
      log_event "INFO" "Removed temporary JSON: $file"
    else
      failed=$((failed + 1))
      log_event "WARN" "Failed to remove temporary JSON: $file"
    fi
  done < <(find "$tmp_dir" -type f -name '*.json' | sort)

  if [[ "$found" -eq 0 ]]; then
    log_event "INFO" "No tmp/**/*.json files found for cleanup"
    return 0
  fi

  log_event "INFO" "Cleanup summary: removed=$removed failed=$failed"
}
